[package]
name = "cool_date"
version = "0.0.1"
authors = ["Maël Sicard-Cras <mael.sicardcras@gmail.com>"]
description = "Cool Date generator library in Rust"
edition = "2018"
license = "Apache-2.0/MIT"
homepage = "https://github.com/MSC29/CoolDate"
repository = "https://github.com/MSC29/CoolDate"
documentation = "https://github.com/MSC29/CoolDate"
readme = "README.md"
keywords = ["date", "time", "calendar", "fun"]
categories = ["date-and-time"]

[lib]
name = "foo"    
path = "src/lib.rs"
edition = "2018"
crate-type = ["lib"]

[dependencies]
chrono = "0.4"